name: Compare files and update pr description
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Run my action
        id: compare-files
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-comment: false
